// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-wrxIugwDh53Mchmnk3WertEucnFxy6g',
    appId: '1:225550925661:web:225a1d4964e4e678faf2b4',
    messagingSenderId: '225550925661',
    projectId: 'task-management-apps-a23c9',
    authDomain: 'task-management-apps-a23c9.firebaseapp.com',
    storageBucket: 'task-management-apps-a23c9.appspot.com',
    measurementId: 'G-072PY9MXL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQhp4IWa-2jJGXK49OE7n8G2aJhk6BVWA',
    appId: '1:225550925661:android:846223d55f1dfe1efaf2b4',
    messagingSenderId: '225550925661',
    projectId: 'task-management-apps-a23c9',
    storageBucket: 'task-management-apps-a23c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwEgDBY4x2nOxJoRxkFj6liBb4-xHvm4',
    appId: '1:225550925661:ios:1eabca9aef65aa37faf2b4',
    messagingSenderId: '225550925661',
    projectId: 'task-management-apps-a23c9',
    storageBucket: 'task-management-apps-a23c9.appspot.com',
    androidClientId: '225550925661-045441jq9pjepcea6h28q94sgi1ege4q.apps.googleusercontent.com',
    iosClientId: '225550925661-lhk9creq6rtrtljevi3j4e7o9igbjg3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTwEgDBY4x2nOxJoRxkFj6liBb4-xHvm4',
    appId: '1:225550925661:ios:1eabca9aef65aa37faf2b4',
    messagingSenderId: '225550925661',
    projectId: 'task-management-apps-a23c9',
    storageBucket: 'task-management-apps-a23c9.appspot.com',
    androidClientId: '225550925661-045441jq9pjepcea6h28q94sgi1ege4q.apps.googleusercontent.com',
    iosClientId: '225550925661-lhk9creq6rtrtljevi3j4e7o9igbjg3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
